### ISSUE TITLE
REQUEST : please add data about wrapped punks, the wrapped punk token

### ISSUE THREAD

**Issue by admazzola** [itsjerryokolo/CryptoPunks#1]
REQUEST : please add data about wrapped punks, the wrapped punk token id

**Comment by itsjerryokolo** [comment]
Okay

**Comment by admazzola** [comment]
Thanks! I would love to query account addresses and then find out not only
what punkIDs they own [current functionality] but also which wrapped
PunkIDs they own (wraptokenid and originaltokenid for each wrapped token)

This is for the frontend of my new exchange buythefloor.com

Mooncats subgraph does this (almost)

**Comment by itsjerryokolo** [comment]
Resolved.
