### ISSUE TITLE
Handle `PunkBought` event bug

### ISSUE THREAD

**Issue by wong2** [itsjerryokolo/CryptoPunks#38]
There's a bug in CryptoPunks contract that causes `PunkBought` event emitted from `acceptBidForPunk` have wrong `value` and `toAddress`. Detail here: https://twitter.com/jwahdatehagh/status/1422590642128105475

This results in missing data when querying `Sales` by `to` field. Can we handle this quirk and inconvenience in this subgraph?

**Comment by itsjerryokolo** [comment]
Thanks for opening this issue.
I have written the code to handle it, and deployed the subgraph.
https://github.com/itsjerryokolo/CryptoPunks/blob/a161819013738c0af7d666c09ef3569086c27782/src/mapping.ts#L311
