### ISSUE TITLE
Missing data querying `transfers` by `txHash`

### ISSUE THREAD

**Issue by wong2** [itsjerryokolo/CryptoPunks#39]
The query:
```
{
  transfers(where:{ txHash: "0xa8cb816346d0efa0d1da3d4f945ab3a3a64d4db39959d62164d37224119c916e" }) {
    id
  }
}
```
returns `"transfers": []`. 

But I can confirm there is `Transfer` event emitted in this transaction: https://etherscan.io/tx/0xa8cb816346d0efa0d1da3d4f945ab3a3a64d4db39959d62164d37224119c916e#eventlog

**Comment by itsjerryokolo** [comment]
Resolved. Related to issue 38: https://github.com/itsjerryokolo/CryptoPunks/issues/38

**Comment by wong2** [comment]
Hi, this query still returns empty. Does the fix apply to history data?

**Comment by itsjerryokolo** [comment]
This transfer is an acceptBidForPunk() event.  You can get the transfer from the cToken entity or the Sale entity.
Try these two queries instead
```graphql
{
  "data": {
    "ctokens": [
      {
        "id": "0xa8cb816346d0efa0d1da3d4f945ab3a3a64d4db39959d62164d37224119c916e-331"
      }
    ]
  }
}
```
```graphql
{
 sales(where:{ txHash: "0xa8cb816346d0efa0d1da3d4f945ab3a3a64d4db39959d62164d37224119c916e" }) {
   id
  
 }
}
```

**Comment by wong2** [comment]
Thanks! Another question, I'd like to query a user's trading history with this query:

```
{
  sales(where: {to: "0xb65893e83bbd9fa5326446251e32cab8ecc01544"}) {
    id
    amount
    nft {
      tokenId
    }
  }
}
```

or 

```
{
  sales(where: {to: "0x1919DB36cA2fa2e15F9000fd9CdC2EdCF863E685"}) {
    id
    amount
    nft {
      tokenId
    }
  }
}
```

The first one returns data, but `amount` is zero. The second one returns empty data, although I know the account has lots of tradings.

What am I missing?

**Comment by itsjerryokolo** [comment]
Okay, I just looked at it. 
The first one is actually a bug from this line.
https://github.com/itsjerryokolo/CryptoPunks/blob/2bc3cfb6c0fe3482730db4a291aeacae41ec7f39/src/mapping.ts#L476

This is the transaction
https://etherscan.io/tx/0xa8cb816346d0efa0d1da3d4f945ab3a3a64d4db39959d62164d37224119c916e#eventlog

I was basically replacing the bid from the sale event.
I just deployed a fix. Thanks for reporting.

For second one,  run the same query again, but this time have a lowercase string for the address like in the first query.

**Comment by wong2** [comment]
Oh, thanks a lot! You saved my day.

**Comment by wong2** [comment]
How long would the data be fixed after deployment?

**Comment by itsjerryokolo** [comment]
It works now. I'm getting this response.
```json
{
  "data": {
    "sales": [
      {
        "id": "0xa8cb816346d0efa0d1da3d4f945ab3a3a64d4db39959d62164d37224119c916e-332-SALE",
        "amount": "75000000000000000000",
        "nft": {
          "tokenId": "9773"
        }
      },
      {
        "id": "0xd15e4864a0de4b229071ba88f774c1868d2e405cfc5a33fc1f4b917d7de6ba0a-193-SALE",
        "amount": "70000000000000000000",
        "nft": {
          "tokenId": "5333"
        }
      }
    ]
  }
}
```

**Comment by wong2** [comment]
Thanks, it works!
